### ISSUE TITLE
Clean up code around donation amounts, removing Decimal and code that permits fractional amounts

### ISSUE THREAD

**Issue by Pomax** [MozillaFoundation/donate-wagtail#1257]
Based on https://github.com/mozilla/donate-wagtail/issues/1187, using `Decimal` means we're using a class that Django treats as "this should be localized" when rendered into a template, which we don't want to have happen.

Given that we already made the decision to only allow integer values, obviating the need for a decimal number, we should go through our code and see where we can remove `Decimal` use, as well as any code that works with amounts that is written to account for decimal values (both on the python side, as well as the JS side)

Some known clean-up sites:

- [get_initial_currency_info](https://github.com/mozilla/donate-wagtail/blob/master/donate/core/models.py#L77-L112)
- [get_intial_amount](https://github.com/mozilla/donate-wagtail/blob/master/donate/core/models.py#L120-L142)
- [assignValues](https://github.com/mozilla/donate-wagtail/blob/master/source/js/components/currency-selector.js#L45-L76), which sets up a localized  number formatter

**Comment by benhohner** [comment]
- [ ] plan time to audit the possible sites
