### ISSUE TITLE
Donate Cinchy/CRM Migration Code Cleanup

### ISSUE THREAD

**Issue by benhohner** [MozillaFoundation/donate-wagtail#1421]
Clean up code for migration on donate and foundation (do After production launch on May 25th)

- [ ] Look through code and environment variables changed on fo'mo because of migration
- [ ] Update fo'mo to remove branching and method env variable

**Comment by Pomax** [comment]
@benhohner do you remember the specifics for this issue?

**Comment by benhohner** [comment]
@Pomax yes, we created conditional branches and extra environment variables, to facilitate the smooth transition by flipping a "feature flag". Now that we have the good path running, we can remove the old path. We also need to clean up the documentation, because may areas reference basket while we're now sending data to Cinchy.
e.g. https://github.com/mozilla/foundation.mozilla.org/blob/d32e205495add6d980c98ceb4da7dd40ccd8bfb7/network-api/networkapi/campaign/views.py#L144 and https://github.com/mozilla/foundation.mozilla.org/blob/d32e205495add6d980c98ceb4da7dd40ccd8bfb7/network-api/networkapi/campaign/views.py#L215
