### ISSUE TITLE
Delete old "Master" branch from git history

### ISSUE THREAD

**Issue by danielfmiranda** [MozillaFoundation/donate-wagtail#1569]
Comment below is outdated: 

_Depends on #1568 
Once we make the change to "Main" we would like to remove the "Master" branch from git history. However, there may be some time between these two tickets as it might be a good idea to have the "master" branch in the history for some time just in case._

### Updated task:

The work for this ticket would be to remove the Master branch from github.

**Comment by bheasman** [comment]
@Pomax to add a few more details to support this ticket

**Comment by danielfmiranda** [comment]
Hi Everyone, it looks like this work has been taken care of:
![Screenshot 2022-10-10 at 16-38-47 Branches · mozilla_foundation mozilla org](https://user-images.githubusercontent.com/18314510/194967950-b74a8cc4-29e3-4399-aca4-b41a101557ef.png)


However, this work is still needed in the donate stack as reflected in https://github.com/MozillaFoundation/donate-wagtail/issues/1568.

Once I finish my other assigned sprint tickets, I will work on #1568

**Comment by Pomax** [comment]
this issue was for the donate repo, which is why it was in donate-wagtail, not foundation.moz =)

**Comment by danielfmiranda** [comment]
Ah, thank you @Pomax!

**Comment by danielfmiranda** [comment]
The work regarding the change from `master` to `main` has been completed in #1568, will delete the branch from history and close this ticket next week

**Comment by danielfmiranda** [comment]
Master has now been removed! Closing this issue
