### ISSUE TITLE
Document the recaptcha functionality

### ISSUE THREAD

**Issue by Pomax** [MozillaFoundation/donate-wagtail#1570]
- where does recaptcha get injected
- how is it established
- how is it communicated to us
- how/when does it get validated

**Comment by Pomax** [comment]
- https://github.com/mozilla/donate-wagtail/blob/1c3c0a24731fd0e5395b03852d92ab8cb67ac8b1/donate/recaptcha/fields.py#L15

- https://github.com/mozilla/donate-wagtail/blob/1c3c0a24731fd0e5395b03852d92ab8cb67ac8b1/donate/recaptcha/utils.py#L12

**Comment by tbrlpld** [comment]
@Pomax Will you be able to finish this in your last week or should we reassign?
