### ISSUE TITLE
The "Donate" link from the footer of the page redirect to a "403 ERROR" while using a VPN connection

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [MozillaFoundation/donate-wagtail#1645]
[Affected Versions]:
- Nightly 99.0a1;
- Chrome 98.0.4758.102

[Affected Platforms]:
- Windows 10 x64
- Linux Mint 20 x64
- macOS 10.15.7

[Prerequisites]:
- Be connected to "US" country using a VPN connection, eg: MozillaVPN.

[Steps to reproduce]:
1. Navigate to https://www.mozilla.org/.
2. Scroll down the page until the footer is displayed.
3. Click the "Donate" button link.
4. Observe the behavior.

[Expected result]:
- You are redirected to the "Donate" page and the page is correctly loaded.
 
[Actual result]:
- You are redirected to the "Donate" page but a "403 ERROR" error is displayed.

[Notes]:
- The issue is NOT reproducible if you are not connected to a VPN service.
- I have managed to reproduce the issue using MozillaVPN and NordVPN.
- Attached is a screen recording of the issue.

https://user-images.githubusercontent.com/19226534/156203028-10e4aac6-eda1-4ae4-b5d4-972192a374e3.mov

**Comment by jzinner** [comment]
This issue is resolved with the completion of mofodevopsprivate 394

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue on the latest Nightly 110.0a1 build, Firefox Release 108.0 and Chrome 108.0.5359.100 on Windows 10 x64, macOS 12.4 and Linux Mint 20 x64.
- After following STR the "Donate" page is correctly loaded.
