### ISSUE TITLE
Donations blocked when donor using a VPN

### ISSUE THREAD

**Issue by stephanielowry** [MozillaFoundation/donate-wagtail#1650]
As noted in the MoFo Engineering Slack channel, donors are being blocked when using a VPN. 

We'd like this block removed during each week of the month when a fundraising appeal and kicker go out. It can be added back after the appeal is over, typically a 7 day period would be good. 

Donors are complaining because Mozilla offers a VPN, yet we're having to ask them to turn it off when donating to us. It's a bad experience for them. 

Error message a donor is seeing is attached
<img width="472" alt="Screen Shot 2022-03-28 at 1 43 21 PM" src="https://user-images.githubusercontent.com/30730118/162532784-49eb5580-7dd5-4c22-a913-d0ed52075e23.png">

Thank you!

**Comment by anilkanji** [comment]
Can we figure out how to track how many people are served this 403 page after we release?
