### ISSUE TITLE
Remove charity navigator logo

### ISSUE THREAD

**Issue by bheasman** [MozillaFoundation/donate-wagtail#1685]
**Background**
As a MoFo staffmember, I want to avoid confusing our financial contributors as to our status as a charity. I'd like to remove the "Charity Navigator" logo from our donate.mozilla.org page.

![image.png](https://images.zenhubusercontent.com/613f78ddde2b3f39d7420389/44a14261-52be-4af5-a710-e03cd8d519f3)

**Acceptance criteria**
- [ ] Charity navigator logo is no longer appearing on donate.mozilla.org

**Comment by SamirPS** [comment]
Hello,

Can I take this issue? @bheasman
