### ISSUE TITLE
Update Acoustic email language IDs

### ISSUE THREAD

**Issue by danielfmiranda** [MozillaFoundation/donate-wagtail#1698]
There has been a request by the email team to update the ID's of the Acoustic email language codes to:

```
EN    2959686
CS    2960691
DE    2960705
ES    2960719
FR    2960725
JP    2960734
PL    2959660
PT    2960746
```

**Comment by tbrlpld** [comment]
Nobody is working on this. Removing from active sprint.

**Comment by danielfmiranda** [comment]
This work was completed in #1697. It appears that this ticket did not close automatically when the PR was merged. Closing now!
