### ISSUE TITLE
[FRU] Add JavaScript Snippet to give.thunderbird.net

### ISSUE THREAD

**Issue by mtdenton** [MozillaFoundation/donate-wagtail#1713]
In order to test and utilize Fundraise Up capabilities, we'll need to add the following snippet globally into the `<head>` of our thunderbird pages:

```
<!-- Fundraise Up: the new standard for online giving -->
<script>(function(w,d,s,n,a){if(!w[n]){var l='call,catch,on,once,set,then,track'
.split(','),i,o=function(n){return'function'==typeof n?o.l.push([arguments])&&o
:function(){return o.l.push([n,arguments])&&o}},t=d.getElementsByTagName(s)[0],
j=d.createElement(s);j.async=!0;j.src='https://cdn.fundraiseup.com/widget/'+a;
t.parentNode.insertBefore(j,t);o.s=Date.now();o.v=4;o.h=w.location.href;o.l=[];
for(i=0;i<7;i++)o[l[i]]=o(l[i]);w[n]=o}
})(window,document,'script','FundraiseUp','ADGJGYAN');</script>
<!-- End Fundraise Up -->
```
Our CSP directives will also have to be updated to allow these scripts to load on the page. Details can be found [here](https://help.fundraiseup.com/can-fundraise-up-be-used-on-a-site-with-a-csp)

A nonce attribute will need to be added to the opening `<script>` in the snippet above. Example:
`<script nonce="{{request.csp_nonce}}"`

### Dev Tasks
- [x] Add the above snippet to globally load the FRU snippet. Include the `nonce` attribute in the `script` tag (is this needed?). It should only be loaded for give.thunderbird.net
- [x] Update the CSP configuration to allow for FRU assets to load in browsers on both the staging and production sites for thunderbird.

### Acceptance Criteria
- [ ] As a developer, I can see the Fundraise Up script load in browser developer tools site-wide on give.thunderbird.net.
- [ ] As a user, if I navigate to https://give.thunderbird.net/?form=support, a lightbox pops up with a Fundraise Up donation form.

**Comment by mtdenton** [comment]
I accidentally clicked epic and now I don't know how to fix it. It shouldn't be an epic.

**Comment by danielfmiranda** [comment]
Tested this on staging, looks to be working as expected to me! 👍

**Comment by mtdenton** [comment]
Looks good on staging here as well. Ready for prod
