### ISSUE TITLE
Country list l10n issues on card payment page

### ISSUE THREAD

**Issue by Sancus** [MozillaFoundation/donate-wagtail#1719]
So, I'm not sure if it actually makes sense to fix this on wagtail, or if the Fundraise Up stack will solve it, but:

https://donate.mozilla.org/fr/card/single/?source_page_id=3&currency=usd&amount=20

On this page, no matter what locale you arrive with, the country choice ALWAYS defaults to US. This is frustrating for non-US donors and it seems like we can make a much better guess for most locales.

Secondly, and possibly a tougher fix, is that the sort order is not localized and thus makes no sense at all in some languages like Japanese [as detailed in this bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=1803993). But, I think this would be substantially mitigated with better defaults.

**Comment by zephyrus00jp** [comment]
It was suggested that the user's address may not be necessary at all when one pays by credit card.
https://bugzilla.mozilla.org/show_bug.cgi?id=1803993#c4

Less information input means easier input, thus easier donation method.

**Comment by zephyrus00jp** [comment]
Quote from https://bugzilla.mozilla.org/show_bug.cgi?id=1803993#c5

Is the list translated by mozilla?
If we are using an external library or something, check it out first.
I wonder if such libraries have no-execution dry-run test mode.

Next time a new UI is installed, it would be great to have a dry-run test by users in various countries, especially where problems were reported such as Japan.
