### ISSUE TITLE
Braintree Python SDK Update

### ISSUE THREAD

**Issue by mtdenton** [MozillaFoundation/donate-wagtail#1723]
It looks like we'll need to update the Braintree Python SDK one last time. From Braintree:

> This is a reminder that a new version of the SDK was released on October 14, 2022 with new security enhancements. Please upgrade to the Braintree Python SDK v.4.17.1 as soon as possible. Starting February 28, 2023, older versions of the SDK may no longer be supported. Please disregard if you've already updated your SDK following our initial outreach on January 10 but take action now if you haven’t yet done so.
>To make this update:
>    If you're currently using v4 of the Python SDK, you need to upgrade the SDK to v4.17.1 or higher. Your integration won't require any other changes.
    If you're currently using v3 or lower of the Braintree Python SDK, please upgrade to Braintree Python SDK v3.59.1. You also should plan to upgrade to v4.17.1 or higher in the near future. See our [migration guide](https://developer.paypal.com/braintree/docs/reference/general/server-sdk-migration-guide/python) for details on necessary integration changes.

**Comment by danielfmiranda** [comment]
Hi @cdanfon this has been merged into staging! Though the ask of this ticket was just to update a dependency, so I do not think there is much to test.

Should I move this to the closed lane?

**Comment by cdanfon** [comment]
@danielfmiranda Sounds good, I've gone ahead and moved it

**Comment by danielfmiranda** [comment]
Hi @cdanfon my mistake, I think this ticket should be moved to the "Ready for production" lane before "Closed".

I have moved this ticket to ready for production, and will close it after todays prod push!

**Comment by tbrlpld** [comment]
I would say we should definitely test the critical paths. This is the SDK of our payment processor. So we should make sure donations are working as expected.

**Comment by tbrlpld** [comment]
Ok, test payments on staging worked $10 and $60,  each with visa and paypal.

**Comment by tbrlpld** [comment]
Looks like this was still not deployed...

**Comment by tbrlpld** [comment]
Deploying this manually to staging now

**Comment by tbrlpld** [comment]
Ok, finally on staging.

**Comment by tbrlpld** [comment]
@danielfmiranda I am having issues with monthly Paypal donations. Tried $5 per month.

**Comment by tbrlpld** [comment]
A $25 monthly paypal donation worked

**Comment by tbrlpld** [comment]
Double checked in a different browser. Still issue with $5 monthly paypal. @danielfmiranda can you look into this?

**Comment by cdanfon** [comment]
We've discussed during daily huddle that this might not be a blocker for the deployment as the bug might have been there before the update. @danielfmiranda to check if this is still happening before v13. If that's the case @danielfmiranda will remove the deployment blocker label and let the team know.

**Comment by tbrlpld** [comment]
@danielfmiranda Sorry, but I don't follow the above explanation. It sounds like the upgrade fixes the issue. However during QA I ran into this issue on staging.

**Comment by tbrlpld** [comment]
Thanks for the update. That looks clearer now.

**Comment by danielfmiranda** [comment]
Hi @tbrlpld sorry about the confusion. I updated the comment above to better reflect the issue.

What I meant was that this error occurs on either v.13 or v.18, the breaking change being when the environment variables are set to the same ones as mofo donate-staging.

* donate-wagtail from 1Password -> v.13 and v.18 work as expected
* thunderbird from staging -> v.13 and v.18 work as expected
* donate-wagtail from staging -> **neither** v.13 or v.18 work

**Comment by tbrlpld** [comment]
Ok. I guess this is not as critical then, because actual donations won't use the seller login data to make donations 😅

We should use some other login info for testing though.
