### ISSUE TITLE
Disable Upsell form on Thunderbird and Foundation donate site

### ISSUE THREAD

**Issue by danielfmiranda** [MozillaFoundation/donate-wagtail#1724]
It has been requested by the donation team to disable the "Upsell view" from both the thunderbird and the foundation donate sites.

The best way to to this in my opinion would be to create a new feature flag in the CMS, where we can select whether or not to use the upsell view. If this feature flag is not checked, we can update the backend python code accordingly to skip this step, and go straight to the thank you page.

**Comment by cdanfon** [comment]
@mtdenton please test

**Comment by danielfmiranda** [comment]
**Steps to test:**

1. Visit https://donate-wagtail.mofostaging.net/en-US/ and make a credit card donation > $20 USD using test credit card information below
2. Once the donation is complete, the site should skip the "Upsell" View, and redirect you to the newsletter sign up view.
3. Log into https://donate-wagtail.mofostaging.net/admin
4. Click "Settings" -> "Feature Flags" -> Check the "Enable Upsell View" Checkbox
5. Visit https://donate-wagtail.mofostaging.net/en-US/ again,  and make a credit card donation > $20 USD.
6. After the donation is complete, the site should now redirect you to the "Upsell View".
7. If feature flag is working as expected, testing is complete!

**Comment by mtdenton** [comment]
LGTM
