### ISSUE TITLE
Single Paypal payments return 500 error

### ISSUE THREAD

**Issue by danielfmiranda** [MozillaFoundation/donate-wagtail#1727]
**Describe the bug**
One-time paypal donations return the following error on the donate site:

![Screenshot 2023-01-18 at 12-00-09 TypeError at _en-US_paypal_thank-you_](https://user-images.githubusercontent.com/18314510/213282457-7b3de61d-631d-4c7a-805f-f20d8e13bda9.png)

When tracing back the error, it appears that the code it is referencing is the `MinimumCurrencyAmountMixin` found in `forms.py`.

**To Reproduce**
1. Go to the donate site homepage
2. Attempt to make a 1 time donation with paypal
3. Note that a 500 error gets returned instead of the "success page"

**Expected behavior**
Users should be able to use paypal to make donations successfully

**Comment by cdanfon** [comment]
@fessehaye please QA this ticket

**Comment by danielfmiranda** [comment]
**Steps to test:**

1. Visit https://donate-wagtail.mofostaging.net/en-US/
2. Log into 1Password
3. Click the blue "Paypal" button to make a one-time donation of any amount, using the "Paypal sandbox"  credentials
4. Select "CREDIT UNION 1" from the payment options, and click "Complete Purchase:
5. If the payment goes through successfully, testing is complete!

**Comment by fessehaye** [comment]
Worked for me
