### ISSUE TITLE
Update current Donor Intake page with delayed response notice

### ISSUE THREAD

**Issue by mtdenton** [MozillaFoundation/donate-wagtail#1759]
Stakeholder: Patrick Doherty

### Context:
The donor care team has asked that we add some text to the current [Donor Intake page](https://donate.mozilla.org/en-US/help/) ahead of All Hands to let users know they will be delayed in their responses.

### Ideal timing: 
Launch on: Thursday, August 17th
Ending on: Tuesday, August 29th. 

### Copy should read: 

```
Our team is experiencing a backlog in donor inquiries. Please expect a delay of up to 5 business days to respond to your inquiry. 

If you are a current donor, you can use the self-service option to log into your donor portal. You can see receipts and make changes to your monthly gift. To access your log in page, refer to your link in a recent donation email.
```

I know this is a tight timeline, but the team has stressed this is a priority as they will not be managing cases during the week of all hands.

Request for reference:
https://mozilla-hub.atlassian.net/servicedesk/customer/portal/20/MOFOTP-5

**Comment by mtdenton** [comment]
@kristinashu @Gbaldassano

**Comment by danielfmiranda** [comment]
Thank you all! @kristinashu @mtdenton @Gbaldassano 

I am ready to start on this ticket but have some design related questions:

- Should this text go at the top of the other page text, at the bottom or somewhere else?
- Are there any other style changes that should be made to this text, or should the styling match the rest?


Thanks again!

**Comment by kristinashu** [comment]
Thank you @danielfmiranda! I can mock up a couple of options for you and the stakeholder to review before you start on the dev work. I suspect just adding the text might not stand out enough and will look like a lot of copy to read.

@Gbaldassano would Patrick want us to also update the copy on the screen after someone submits the form?

<img width="1486" alt="image" src="https://github.com/MozillaFoundation/donate-wagtail/assets/1068783/19a8f5dc-e8b5-42bf-84c2-a34f10d5ce02">

Will they also update the auto-response email people get right after they submit the form?

**Comment by mtdenton** [comment]
> @mtdenton One question about timing, their ideal launch is 8/17 but that is a Thursday. Are we planning on doing our last deploy before all hands on Tuesday, 8/15? If so I can let them know, just curious.

@Gbaldassano Since this is in our `donate-wagtail` repo connected to donate.mozilla.org (as opposed to the `foundation.mozilla.org` site and repo) we can deploy this whenever we see fit since this will be the only work to be pushed to that prod environment. With the limited scope of these changes, I don't see much risk in sending this out next Thursday if we do it east coast morning to make sure everything is running fine throughout the rest of the day. We can get this PR ready to merge and I'll merge it and push to prod next week when it's time.

**Comment by mtdenton** [comment]
Calling out real quick before we show these to Mia that I don't think we have the banner functionality for Option 2 on the donate site and implementing something like that on donate would expand the scope of this beyond the original estimate. @danielfmiranda correct me if I'm wrong there.

**Comment by mtdenton** [comment]
> I checked with Mia and she confirmed adding the copy to the second screen is a 'nice to have' but not essential. I would say we should do whatever is most time effective and easiest to add/remove.

@Gbaldassano we could create a follow-up ticket for this and if there's room in the sprint maybe we can pick it up?

**Comment by kristinashu** [comment]
My preference is the third option so I'd be happy to remove the top banner version.

**Comment by kristinashu** [comment]
One more option! But really, if Mia is happy with plain text then I'm happy. 

![Lower banner](https://github.com/MozillaFoundation/donate-wagtail/assets/1068783/85602c7b-efa5-4e3a-bb3c-d09fbd3754d4)

**Comment by mtdenton** [comment]
Well looks like we went with option 3! PR looks good but delaying approval. I'll look to get this on staging next Wednesday for QA, make any adjustments if needed (unlikely). Because of the way donate is set up, this will be pushed to prod on the morning of Thursday 8/17 because of the nightly automated staging->prod promote on Heroku. cc @Gbaldassano @kristinashu
