### ISSUE TITLE
EOY - Needs to be live before 11/27 - Update copy on Ways to Give page

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/donate-wagtail#1764]
Text on https://donate.mozilla.org/ways-to-give needs to be updated before Giving Tuesday (11/28)
[Copy doc](https://docs.google.com/document/d/1qUBg3BJwHe0LpfR3N1Mkyly2DL8HsGqhJdpG8vMHsQY/edit) with different UTMs depending on language.

Mock up [in Figma.](https://www.figma.com/file/ueNCG5v3GI8Zc2XmFaNyVS/Donate?type=design&node-id=657%3A3226&mode=design&t=n5K2b821Kqu4Q7o5-1)
 
![Ways to give](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/1068783/5eb5b8ab-01f0-4951-9317-d4e86fea5280)

cc @Gbaldassano @mtdenton

**Comment by Gbaldassano** [comment]
@mtdenton just a heads up, the content in the google doc has been updated since @kristinashu made the mock up in Figma

**Comment by mtdenton** [comment]
@Gbaldassano @kristinashu is the copy final on this now?

**Comment by kristinashu** [comment]
Might just go with this CMS editable page instead https://foundation.mozilla.org/donate/ways-to-give/ and then redirect to it but still waiting for approval from stakeholder.

**Comment by kristinashu** [comment]
Confirmed with the stakeholder that we will use the cms page. Closing this ticket since it is no longer needed and I've opened a new ticket for the redirect https://github.com/MozillaFoundation/donate-wagtail/issues/1765
