### ISSUE TITLE
Can’t link to specific sections in content pages

### ISSUE THREAD

**Issue by TheoChevalier** [MozillaFoundation/donate-wagtail#521]
We can’t use anchors to link to specific sections, because headers don’t have an `id` attribute. Right now the homepage links to
https://give.mozilla.org/ways-to-give#wire and https://give.mozilla.org/ways-to-give#check

We’d need to add an `id` here, https://github.com/mozilla/donate-wagtail/blob/master/donate/templates/blocks/heading_block.html but not sure how… We can’t really use `{{ value }}` as it’s different for each locale, and there is no for loop

**Comment by solarissmoke** [comment]
One option might be to add an `identifier` field to the `HeadingBlock` and use that in the template.
