### ISSUE TITLE
audit the code around payments for "not paypal" implying "credit card"

### ISSUE THREAD

**Issue by Pomax** [MozillaFoundation/donate-wagtail#648]
There's at least one spot where we make the assumption that if a payment is not a PayPal payment, then it has to be a credit card payment, with the code accessing credit card details for the associated transaction, but this means that once we allow more payment methods than just PayPal and credit card, the code may start erroring out.

We'll want to audit the code to see if we made this assumption only in BrainTreeWebhookProcessor or whether we need to update other parts of the code as well.

**Comment by mmmavis** [comment]
(Disclaimer: I'm not familiar with the codebase) 

There's also `METHODS = (METHOD_CARD, METHOD_PAYPAL)` in `constants.py`, though I don't see `METHODS` being used anywhere in the codebase.

**Comment by mmmavis** [comment]
Will this error out if we have more payment methods?

https://github.com/mozilla/donate-wagtail/blob/master/donate/payments/views.py#L532-L536

```py
last_transaction = self.request.session['completed_transaction_details']
        if not(
            last_transaction['payment_frequency'] == constants.FREQUENCY_SINGLE
            and last_transaction['payment_method'] == constants.METHOD_CARD
        ):
            return HttpResponseRedirect(self.get_success_url())
```

https://github.com/mozilla/donate-wagtail/blob/master/donate/payments/views.py#L532-L536

**Comment by Pomax** [comment]
not sure, that looks like code specifically based on "this IS for a credit card" rather than "this is NOT for a credit card".

**Comment by alanmoo** [comment]
@gideonthomas This is probably necessary for Apple/Google Pay work
